# -*- coding: utf-8 -*-
"""Dc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12WkrjwU5JqMLpl1yfkM25_UXPepmkJ2B
"""

import csv

data = [
    {"Name": "John", "Wrist_to_Elbow": 29, "Ankle_to_Elbow": 111, "Height": 185},
    {"Name": "Emma", "Wrist_to_Elbow": 25.5, "Ankle_to_Elbow": 95, "Height": 157},
    {"Name": "Michael", "Wrist_to_Elbow": 25, "Ankle_to_Elbow": 107, "Height": 170},
    {"Name": "Sophia", "Wrist_to_Elbow": 26, "Ankle_to_Elbow": 105, "Height": 162},
    {"Name": "Emily", "Wrist_to_Elbow": 27, "Ankle_to_Elbow": 104, "Height": 164.5},
    {"Name": "Daniel", "Wrist_to_Elbow": 30, "Ankle_to_Elbow": 107, "Height": 180},
    {"Name": "Matthew", "Wrist_to_Elbow": 25, "Ankle_to_Elbow": 100, "Height": 172},
    {"Name": "Andrew", "Wrist_to_Elbow": 25.5, "Ankle_to_Elbow": 103, "Height": 172},
    {"Name": "Alex", "Wrist_to_Elbow": 29, "Ankle_to_Elbow": 112, "Height": 187},
    {"Name": "Ryan", "Wrist_to_Elbow": 26.5, "Ankle_to_Elbow": 108, "Height": 183},
    {"Name": "Christopher", "Wrist_to_Elbow": 29, "Ankle_to_Elbow": 103, "Height": 169.5},
    {"Name": "Jason", "Wrist_to_Elbow": 26, "Ankle_to_Elbow": 99, "Height": 159.5},
    {"Name": "Patrick", "Wrist_to_Elbow": 28, "Ankle_to_Elbow": 104, "Height": 173},
    {"Name": "Sarah", "Wrist_to_Elbow": 23, "Ankle_to_Elbow": 92, "Height": 145},
    {"Name": "David", "Wrist_to_Elbow": 30, "Ankle_to_Elbow": 110, "Height": 183}
]

# Specify the output CSV file path
output_csv_path = "output_dataset.csv"

# Write the data to a CSV file
with open(output_csv_path, mode='w', newline='') as file:
    writer = csv.DictWriter(file, fieldnames=["Name", "Wrist_to_Elbow", "Ankle_to_Elbow", "Height"])
    writer.writeheader()
    writer.writerows(data)

print("CSV file created successfully at", output_csv_path)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
import pandas as pd

df = pd.read_csv("/content/output_dataset.csv")

df.head()

df = df.drop('Name',axis=1)
df.head()

x = df.iloc[:,:-1]
y = df.iloc[:,-1]
y.head()

model = LinearRegression()

# Fit the model to the data
model.fit(x, y)

X_new = np.array([[26, 95], [28, 110]])  # New input features for prediction
predictions = model.predict(X_new)

print(predictions)

coefficients = model.coef_
intercept = model.intercept_

print("Coefficients:", coefficients)
print("Intercept:", intercept)